# Generated by Django 3.2.4 on 2021-06-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210625_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='registro_usuario',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username')),
                ('mail', models.CharField(max_length=100, verbose_name='Correo')),
                ('pwd1', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
