# Generated by Django 3.2.4 on 2021-06-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210626_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_usuario',
            old_name='pwd1',
            new_name='password',
        ),
    ]
